### ISSUE TITLE
Prettier and lint github actions

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#339] opened 2024-04-05 22:59 UTC
Prettier and lint github actions are currently failing due to un unknown error

 - Test to see if it's polling wrong commit id
 - Enable verbose
 
 Check strict mode

**Comment by Seroxdesign** [comment] 2024-04-16 12:36
I confirmed this issue is due to a default eslint rule which tolerates 0 warnings via #368 

Unfortunately ESLint is unable to automatically fix unused variables, and important warnings: https://stackoverflow.com/questions/47967694/eslint-fix-not-resolving-warnings-according-to-eslintrc-rules

So our 2 options here:

- Raise warning tolerance amount above 0
- Just manually run lint --fix and fix the warnings prior to pushing.

I'm for not raising the warning tolerance in this situation. Will differ to @pi0neerpat

**Closed** 2024-04-16 15:43 UTC
Labels: tech-debt
