### ISSUE TITLE
QA - Depost and Borrow tx

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#83] opened 2023-08-22 21:18 UTC
Deposit and Borrow transaction is failing immediately- maybe a token approval "cap" issue caused by MM

**Comment by jahabeebs** [comment] 2023-08-29 17:34
> Deposit and Borrow transaction is failing immediately- maybe a token approval "cap" issue caused by MM

@pi0neerpat I found that the issue is because the transaction reverts when you try to just deposit without borrowing anything. Maybe in the Solidity code these action are coupled to each other for some reason. Here's an example of depositing WBTC without borrowing OD (results in failure)

https://github.com/open-dollar/od-app/assets/47253537/999fa878-4bfc-4409-a24c-2d28af41ee09

Here's an example of depositing WBTC but also borrowing OD (success)

https://github.com/open-dollar/od-app/assets/47253537/fdefc30c-a48a-4044-8ae0-0f44f247f791

**Comment by jahabeebs** [comment] 2023-08-29 18:48
closing, will add validation in https://github.com/open-dollar/od-app/issues/99

**Closed by jahabeebs** 2023-08-29 18:48 UTC
Labels: ch-18
